// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgT2MmV9pgGMBg8pg7tyl-yTGboSN6e4o',
    appId: '1:746598482292:web:2dbcf637b44310d1ee6c21',
    messagingSenderId: '746598482292',
    projectId: 'ohlala123',
    authDomain: 'ohlala123.firebaseapp.com',
    storageBucket: 'ohlala123.firebasestorage.app',
    measurementId: 'G-JN49N9PNXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcGh7yfhLVv6Qo2OTqN7LCapoKgmpIvw0',
    appId: '1:746598482292:android:2779ba78cc2a6404ee6c21',
    messagingSenderId: '746598482292',
    projectId: 'ohlala123',
    storageBucket: 'ohlala123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdkQmx3IuDz33rB7on6COoSa-WHE7Vr6g',
    appId: '1:746598482292:ios:62f2e3ebb7c9f23bee6c21',
    messagingSenderId: '746598482292',
    projectId: 'ohlala123',
    storageBucket: 'ohlala123.firebasestorage.app',
    iosBundleId: 'com.example.project001',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdkQmx3IuDz33rB7on6COoSa-WHE7Vr6g',
    appId: '1:746598482292:ios:62f2e3ebb7c9f23bee6c21',
    messagingSenderId: '746598482292',
    projectId: 'ohlala123',
    storageBucket: 'ohlala123.firebasestorage.app',
    iosBundleId: 'com.example.project001',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgT2MmV9pgGMBg8pg7tyl-yTGboSN6e4o',
    appId: '1:746598482292:web:7b7c8d5b6c21f4cfee6c21',
    messagingSenderId: '746598482292',
    projectId: 'ohlala123',
    authDomain: 'ohlala123.firebaseapp.com',
    storageBucket: 'ohlala123.firebasestorage.app',
    measurementId: 'G-YNQEDTWMVE',
  );
}
